(dp0
Vid
p1
V3f61bb5ba0cb74
p2
sVname
p3
VCNTManager3
p4
sVinfo
p5
VConnect Manager
p6
sVtags
p7
Vtools
p8
sVicon
p9
V
p10
sVcommand
p11
Vimport importlib\u000afrom character import CNTManager3\u000aimportlib.reload(CNTManager3)\u000aCNTManager3.runWin()
p12
sVsyntax
p13
Vpython
p14
s.