(dp0
Vid
p1
V3ede3cbc4fce0c
p2
sVname
p3
VConvertStandardShader
p4
sVinfo
p5
Vtools
p6
sVtags
p7
V,\ubbfc\uc131
p8
sVicon
p9
V
p10
sVcommand
p11
Vimport importlib\u000afrom tools.convert_aistandard_to_lambert import reload_and_show\u000areload_and_show()
p12
sVsyntax
p13
Vpython
p14
s.