(dp0
Vid
p1
V3f1924fdb6a6e4
p2
sVname
p3
VCreateControl
p4
sVinfo
p5
Vcontroller create tool
p6
sVtags
p7
Vtools
p8
sVicon
p9
V
p10
sVcommand
p11
Vimport importlib\u000aimport ctrl_generator_tool\u000aimportlib.reload(ctrl_generator_tool)\u000actrl_generator_tool.show()
p12
sVsyntax
p13
Vpython
p14
s.