(dp0
Vid
p1
V3f617e4d7d6c6a
p2
sVname
p3
Vctrl_generator_tool
p4
sVinfo
p5
Vctrl tool
p6
sVtags
p7
Vtools
p8
sVicon
p9
V
p10
sVcommand
p11
Vimport importlib\u000aimport ctrl_generator_tool\u000aimportlib.reload(ctrl_generator_tool)\u000actrl_generator_tool.show()
p12
sVsyntax
p13
Vpython
p14
s.