(dp0
Vid
p1
V3edfe4c084bfbe
p2
sVname
p3
VMHADV3
p4
sVinfo
p5
VMHADV3 \uc218\uc815 \ud544\uc694
p6
sVtags
p7
V\ubbfc\uc131
p8
sVicon
p9
V
p10
sVcommand
p11
Vimport importlib\u000afrom character import MHADV3\u000aimportlib.reload(MHADV3)\u000aMHADV3.runWin()
p12
sVsyntax
p13
Vpython
p14
s.