(dp0
Vid
p1
V3ede3b43593da4
p2
sVname
p3
Vmh Tools Integrated
p4
sVinfo
p5
Vmh tool
p6
sVtags
p7
V,\ubbfc\uc131
p8
sVicon
p9
V
p10
sVcommand
p11
Vimport importlib\u000afrom tools import mh_tools_integrated\u000aimportlib.reload(mh_tools_integrated)\u000amh_tools_integrated.show()
p12
sVsyntax
p13
Vpython
p14
s.