(dp0
Vid
p1
V3edfc2caf9c5dc
p2
sVname
p3
VRenamer
p4
sVinfo
p5
Vrename tool
p6
sVtags
p7
V,\ubbfc\uc131
p8
sVicon
p9
V
p10
sVcommand
p11
Vimport importlib\u000afrom tools import reNamer\u000aimportlib.reload(reNamer)
p12
sVsyntax
p13
Vpython
p14
s.