(dp0
Vid
p1
V3edfe43bbb0284
p2
sVname
p3
Vvertex_reorder_tool
p4
sVinfo
p5
Vvertex_reorder_tool
p6
sVtags
p7
V\ubbfc\uc131
p8
sVicon
p9
V
p10
sVcommand
p11
Vimport importlib\u000afrom rigging import vertex_reorder_tool\u000aimportlib.reload(vertex_reorder_tool)\u000a
p12
sVsyntax
p13
Vpython
p14
s.