(dp0
Vid
p1
V3f60245955c312
p2
sVname
p3
Vctrl_creator_tool
p4
sVinfo
p5
Vctrl_creator_tool 
p6
sVtags
p7
Vtools
p8
sVicon
p9
V
p10
sVcommand
p11
Vimport importlib\u000afrom python2.tools import ctrl_creator_tool\u000aimportlib.reload(ctrl_creator_tool)\u000actrl_creator_tool.show()
p12
sVsyntax
p13
Vpython
p14
s.