(dp0
Vid
p1
V3f601ed50ec2a8
p2
sVname
p3
VreNamer
p4
sVinfo
p5
VreNamer tool
p6
sVtags
p7
Vtools
p8
sVicon
p9
V
p10
sVcommand
p11
Vfrom importlib import reload\u000afrom python3.tools import reNamer\u000areload(reNamer)
p12
sVsyntax
p13
Vpython
p14
s.